### ISSUE TITLE
Not all ids are extracted from react-intl defineMessages

### ISSUE THREAD

**Issue by cwitteveen** [simplelocalize/simplelocalize-cli#101]
The regex defined in the `ReactIntlKeyExtractor` to extract ids from the `defineMessages` function only ever matches the first id defined, and it also only matches when the id is on the same line as the key in the object. So nicely formatting your code breaks the extraction.

Regex in the code:
https://github.com/simplelocalize/simplelocalize-cli/blob/2e8bf5fcfc7daf9cbf21453a80ddf7dbc4ce0908/src/main/java/io/simplelocalize/cli/extraction/keys/ReactIntlKeyExtractor.java#L32

I entered the regex on regex101.com and tested it with a code sample.
1. Screenshot with original test string -> no matches
![image](https://github.com/simplelocalize/simplelocalize-cli/assets/12895107/63e74759-2959-4c31-805e-8c8b87cb1e99)
2. Removed the newlines within the message object -> only first id matches
![image](https://github.com/simplelocalize/simplelocalize-cli/assets/12895107/e8113f22-cf11-4913-98fc-38cdd8b43244)

**Comment by jpomykala** [comment]
Hey @cwitteveen 

thanks for the report. Could you please paste the file or part of the file for which the extraction doesn't work?

>  it also only matches when the id is on the same line as the key in the object

It's not an issue, because code is converted to a one line before looking for IDs:

https://github.com/simplelocalize/simplelocalize-cli/blob/2e8bf5fcfc7daf9cbf21453a80ddf7dbc4ce0908/src/main/java/io/simplelocalize/cli/extraction/keys/ReactIntlKeyExtractor.java#L18
